import {z} from "zod";

export const GenerationResultSchema = z.object({
  files: z.record(z.string(), z.string()),
  description: z.string().default("Generated Project by AI"),
});

export const FileOperationSchema = z.object({
  operation: z.enum(["create", "update", "delete"]),
  filePath: z.string(),
  content: z.string().nullable().optional(),
  search:  z.string().nullable().optional(),
  replace: z.string().nullable().optional(),
});


export const RevisionResultSchema = z.object({
  operation: z.enum(["create", "update", "delete"]),
  description: z.string().default("Applied Revision Project by AI"),

});

export const FilePlanSchema = z.object({
  files: z.array(
    z.object({
      path: z.string(),
      description: z.string(),
      exports:z.string().optional().default(""),
      imports:z.array(z.string()).optional().default([]),
    })
  ),
  projectName: z.string().default("Generated Project by AI"),
  projectDescription: z.string().default("A React project generated by AI"),
});
    
export const FileCodeSchema = z.object({
  code: z.string(),
})